

POST http://localhost:3001/api/artists
Content-Type: application/json

 {
    "name": "newName", 
    "cover_img": "image",
    "username": "user.username",
    "upload_at": "2020-10-01"
}

###

GET http://localhost:3001/api/albums